/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Default: typeof import('./../src/app/layouts/default.vue')['default']
    HomeView: typeof import('./../src/app/pages/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserView: typeof import('./../src/app/pages/UserView.vue')['default']
  }
}
